import type {
  User,
  UserRole,
  ServiceCategory,
  PackageItem,
  Addon,
  StudioRoom,
  Employee,
  CustomerProfile,
  Booking,
  Album,
  Promotion,
  AuditLog,
  NotificationItem,
} from './types';

export const DEMO_ACCOUNTS = [
  {
    role: 'GUEST' as UserRole,
    name: 'Khách Tham Quan',
    email: 'guest@maisonmipa.vn',
    description: 'Chỉ xem thông tin công khai (Hero, Dịch vụ, Bảng giá, Portfolio)',
    color: '#6E5F55',
    badge: 'Guest Mode',
  },
  {
    role: 'CUSTOMER' as UserRole,
    name: 'Nguyễn Minh Anh',
    email: 'minhanh.nguyen@gmail.com',
    description: 'Khách hàng VIP — Xem đơn đặt lịch cá nhân & duyệt album ảnh',
    color: '#8C6E53',
    badge: 'Khách Hàng',
  },
  {
    role: 'STAFF' as UserRole,
    name: 'Hoàng Minh (Photographer)',
    email: 'minh.photographer@maisonmipa.vn',
    description: 'Nhân viên — Lịch làm việc, nhận ca chụp & upload ảnh',
    color: '#C6A45F',
    badge: 'Photographer',
  },
  {
    role: 'MANAGER' as UserRole,
    name: 'Lê Tấn Phát (Studio Manager)',
    email: 'phat.manager@maisonmipa.vn',
    description: 'Quản lý Studio — Quản lý doanh thu, Lịch phòng & CRM Khách hàng',
    color: '#2C221E',
    badge: 'Studio Manager',
  },
  {
    role: 'ADMIN' as UserRole,
    name: 'Maison MIPA Administrator',
    email: 'admin@maisonmipa.vn',
    description: 'Quản trị viên — Phân quyền, cài đặt hệ thống & Voucher',
    color: '#9D174D',
    badge: 'System Admin',
  },
];

export const CURRENT_USER_PROFILES: Record<string, User> = {
  GUEST: {
    id: 'user_guest',
    fullName: 'Khách Tham Quan',
    email: 'guest@maisonmipa.vn',
    phone: 'Khách chưa đăng nhập',
    role: 'GUEST',
    status: 'ACTIVE',
    avatar: '/hero.png',
  },
  CUSTOMER: {
    id: 'user_cust_01',
    fullName: 'Nguyễn Minh Anh',
    email: 'minhanh.nguyen@gmail.com',
    phone: '0908 123 456',
    role: 'CUSTOMER',
    status: 'ACTIVE',
    avatar: '/studio.png',
    emails: [{ id: 'em_1', userId: 'user_cust_01', email: 'minhanh.nguyen@gmail.com', isPrimary: true, verifiedAt: '2026-08-11T10:00:00Z' }],
    phones: [{ id: 'ph_1', userId: 'user_cust_01', phoneRaw: '0908 123 456', phoneE164: '+84908123456', isPrimary: true, verifiedAt: '2026-08-11T10:00:00Z' }],
  },
  STAFF: {
    id: 'user_staff_photographer',
    fullName: 'Hoàng Minh (Photographer)',
    email: 'minh.photographer@maisonmipa.vn',
    phone: '0912 345 678',
    role: 'STAFF',
    staffRole: 'PHOTOGRAPHER',
    status: 'ACTIVE',
    avatar: '/hero.png',
    emails: [{ id: 'em_2', userId: 'user_staff_photographer', email: 'minh.photographer@maisonmipa.vn', isPrimary: true, verifiedAt: '2026-08-11T10:00:00Z' }],
    phones: [{ id: 'ph_2', userId: 'user_staff_photographer', phoneRaw: '0912 345 678', phoneE164: '+84912345678', isPrimary: true, verifiedAt: '2026-08-11T10:00:00Z' }],
  },
  MANAGER: {
    id: 'user_manager',
    fullName: 'Lê Tấn Phát (Studio Manager)',
    email: 'phat.manager@maisonmipa.vn',
    phone: '0988 999 888',
    role: 'MANAGER',
    staffRole: 'MANAGER',
    status: 'ACTIVE',
    mfaEnabled: true,
    avatar: '/studio.png',
    emails: [{ id: 'em_3', userId: 'user_manager', email: 'phat.manager@maisonmipa.vn', isPrimary: true, verifiedAt: '2026-08-11T10:00:00Z' }],
    phones: [{ id: 'ph_3', userId: 'user_manager', phoneRaw: '0988 999 888', phoneE164: '+84988999888', isPrimary: true, verifiedAt: '2026-08-11T10:00:00Z' }],
  },
  ADMIN: {
    id: 'user_admin',
    fullName: 'Maison MIPA Administrator',
    email: 'admin@maisonmipa.vn',
    phone: '0933 000 111',
    role: 'ADMIN',
    staffRole: 'ADMIN',
    status: 'ACTIVE',
    mfaEnabled: true,
    avatar: '/hero.png',
    emails: [{ id: 'em_4', userId: 'user_admin', email: 'admin@maisonmipa.vn', isPrimary: true, verifiedAt: '2026-08-11T10:00:00Z' }],
    phones: [{ id: 'ph_4', userId: 'user_admin', phoneRaw: '0933 000 111', phoneE164: '+84933000111', isPrimary: true, verifiedAt: '2026-08-11T10:00:00Z' }],
  },
};

export const INITIAL_USERS: User[] = [
  CURRENT_USER_PROFILES.CUSTOMER,
  CURRENT_USER_PROFILES.STAFF,
  CURRENT_USER_PROFILES.MANAGER,
  CURRENT_USER_PROFILES.ADMIN,
];

export const INITIAL_SERVICES: ServiceCategory[] = [
  {
    id: 'srv_couple',
    name: 'Couple Photography',
    slug: 'couple',
    description: 'Lưu giữ khoảnh khắc ngọt ngào, ấm áp & tự nhiên của hai bạn trong không gian studio thơ mộng.',
    icon: 'Heart',
    image: '/hero.png',
    badge: 'Yêu thích nhất',
  },
  {
    id: 'srv_wedding',
    name: 'Pre-Wedding & Studio Wedding',
    slug: 'wedding',
    description: 'Bộ ảnh cưới tinh tế, sang trọng mang phong cách Châu Âu lãng mạn & cổ điển.',
    icon: 'Sparkles',
    image: '/studio.png',
    badge: 'Premium',
  },
  {
    id: 'srv_family',
    name: 'Family & Generational',
    slug: 'family',
    description: 'Kỷ niệm gia đình ấm áp, lưu giữ nụ cười và sự gắn kết qua từng thế hệ.',
    icon: 'Users',
    image: '/hero.png',
  },
  {
    id: 'srv_baby',
    name: 'Baby & Newborn Memories',
    slug: 'baby',
    description: 'Ghi lại những bước chân đầu đời, thiên thần nhỏ với đạo cụ & trang phục an toàn.',
    icon: 'Smile',
    image: '/studio.png',
  },
  {
    id: 'srv_portrait',
    name: 'Personal Portrait & Concept',
    slug: 'portrait',
    description: 'Chân dung nghệ thuật cá nhân, tôn vinh nét đẹp & thần thái độc bản của riêng bạn.',
    icon: 'Camera',
    image: '/hero.png',
  },
  {
    id: 'srv_birthday',
    name: 'Birthday & Event Celebration',
    slug: 'birthday',
    description: 'Khung hình sinh nhật lung linh với bóng bay, bánh kem và phông nền trang trí độc quyền.',
    icon: 'Gift',
    image: '/studio.png',
  },
  {
    id: 'srv_graduation',
    name: 'Graduation & Concept',
    slug: 'graduation',
    description: 'Bộ ảnh kỷ yếu tốt nghiệp thanh xuân với phong cách hiện đại, trẻ trung, lưu giữ dấu ấn rực rỡ của tuổi trẻ.',
    icon: 'Sparkles',
    image: '/hero.png',
    badge: 'Trending',
  },
];

export const INITIAL_PACKAGES: PackageItem[] = [
  {
    id: 'pkg_basic',
    serviceId: 'srv_couple',
    name: 'MIPA BASIC',
    price: 1290000,
    durationMinutes: 60,
    conceptsCount: 1,
    editedPhotosCount: 10,
    features: [
      '60 phút chụp hình tận tâm',
      '1 Concept trang trí Studio tùy chọn',
      '10 Ảnh chỉnh sửa mịn da & tone màu pastel',
      'Tặng toàn bộ file ảnh gốc chất lượng cao',
      '1 Photographer chuyên nghiệp hỗ trợ pose dáng',
      'Trang phục 1 bộ tự chọn tại Studio',
    ],
  },
  {
    id: 'pkg_signature',
    serviceId: 'srv_couple',
    name: 'MIPA SIGNATURE',
    price: 2490000,
    durationMinutes: 120,
    conceptsCount: 2,
    editedPhotosCount: 20,
    recommended: true,
    popularTag: 'Được đặt nhiều nhất',
    features: [
      '120 phút chụp thoải mái không vội vã',
      '2 Concept độc quyền cao cấp',
      'Bao gồm Gói Trang điểm & Làm tóc chuyên nghiệp',
      '20 Ảnh chỉnh sửa hậu kỳ kĩ lưỡng',
      'Tặng 01 Khung ảnh để bàn gỗ cao cấp 15x21cm',
      'Tặng toàn bộ file ảnh gốc full HD',
      'Trang phục 2 bộ tự chọn',
    ],
  },
  {
    id: 'pkg_premium',
    serviceId: 'srv_couple',
    name: 'MIPA PREMIUM LUXURY',
    price: 3990000,
    durationMinutes: 180,
    conceptsCount: 3,
    editedPhotosCount: 30,
    features: [
      '180 phút trọn vẹn trong phòng Studio riêng',
      '3 Concept sang trọng tự do sáng tạo',
      'Trang điểm + Đổi 2 kiểu tóc theo concept',
      '30 Ảnh chỉnh sửa hiệu ứng điện ảnh đặc biệt',
      '01 Album photobook mở phẳng cao cấp (20x30cm)',
      'Tặng video ngắn Slideshow kỷ niệm 4K',
      'Hỗ trợ toàn bộ hoa tươi & đạo cụ thiết kế riêng',
    ],
  },
];

export const INITIAL_ADDONS: Addon[] = [
  {
    id: 'add_makeup',
    name: 'Trang điểm & Làm tóc chuyên nghiệp',
    price: 400000,
    description: 'Chuyên viên Makeup theo phong cách Hàn Quốc/Châu Âu mỏng nhẹ, tôn nét đẹp tự nhiên.',
    category: 'makeup',
  },
  {
    id: 'add_hair',
    name: 'Đổi kiểu tóc phụ (Hair Styling)',
    price: 200000,
    description: 'Thay đổi kiểu tóc tương ứng với concept thứ 2 hoặc 3.',
    category: 'styling',
  },
  {
    id: 'add_concept',
    name: 'Thêm 01 Concept trang trí studio',
    price: 300000,
    description: 'Tăng thêm 1 bối cảnh & ánh sáng nghệ thuật khác biệt.',
    category: 'concept',
  },
  {
    id: 'add_time',
    name: 'Thêm 30 phút chụp bổ sung',
    price: 250000,
    description: 'Dành nhiều thời gian hơn để bắt trọn từng cảm xúc thả lỏng.',
    category: 'time',
  },
  {
    id: 'add_album',
    name: 'In Album PhotoBook cao cấp (20x20cm)',
    price: 500000,
    description: 'Mặt ảnh ép lụa chống nước, bìa da tinh tế dập nổi logo Maison MIPA.',
    category: 'album',
  },
  {
    id: 'add_express',
    name: 'Dịch vụ Chỉnh ảnh hỏa tốc (24h)',
    price: 350000,
    description: 'Ưu tiên chỉnh sửa hoàn thành trong 24 giờ sau buổi chụp.',
    category: 'edit',
  },
];

export const INITIAL_STUDIO_ROOMS: StudioRoom[] = [
  {
    id: 'std_room_1',
    name: 'Maison Room 01 (Warm French)',
    code: 'ROOM_01',
    capacity: 6,
    status: 'ACTIVE',
    image: '/studio.png',
    description: 'Phòng chụp chủ đạo tone vàng kem, rèm lụa bồng bềnh, kiến trúc vòm cửa Pháp cổ kính & sofa nhung.',
  },
  {
    id: 'std_room_2',
    name: 'Maison Room 02 (Vintage Loft)',
    code: 'ROOM_02',
    capacity: 5,
    status: 'ACTIVE',
    image: '/studio.png',
    description: 'Không gian gạch mộc, ánh sáng tự nhiên rực rỡ, tông nâu trầm ấm thích hợp ảnh Concept & Vintage.',
  },
  {
    id: 'std_garden',
    name: 'Outdoor Maison Garden',
    code: 'GARDEN',
    capacity: 10,
    status: 'ACTIVE',
    image: '/hero.png',
    description: 'Khu sân vườn rợp cây xanh, cỏ lau tự nhiên & góc tiệc trà chiều lãng mạn ngoài trời.',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp_minh',
    name: 'Hoàng Minh',
    phone: '0912 345 678',
    email: 'minh.photographer@maisonmipa.vn',
    role: 'PHOTOGRAPHER',
    avatar: '/hero.png',
    skills: ['Couple', 'Portrait', 'Wedding', 'Outdoor'],
    rating: 4.9,
    totalSessions: 142,
    status: 'ACTIVE',
    shiftSchedule: { T2: '09:00 - 18:00', T3: 'OFF', T4: '09:00 - 18:00', T5: '09:00 - 18:00', T6: '09:00 - 18:00', T7: '08:00 - 20:00', CN: '08:00 - 20:00' },
  },
  {
    id: 'emp_hung',
    name: 'Trần Hùng',
    phone: '0913 888 777',
    email: 'hung.photographer@maisonmipa.vn',
    role: 'PHOTOGRAPHER',
    avatar: '/studio.png',
    skills: ['Baby', 'Family', 'Birthday'],
    rating: 4.8,
    totalSessions: 98,
    status: 'ACTIVE',
    shiftSchedule: { T2: '09:00 - 18:00', T3: '09:00 - 18:00', T4: 'OFF', T5: '09:00 - 18:00', T6: '09:00 - 18:00', T7: '08:00 - 20:00', CN: '08:00 - 20:00' },
  },
  {
    id: 'emp_huong',
    name: 'Phạm Thanh Hương',
    phone: '0977 111 222',
    email: 'huong.makeup@maisonmipa.vn',
    role: 'MAKEUP',
    avatar: '/hero.png',
    skills: ['Korean Light', 'Vintage Glam', 'Bridal Makeup'],
    rating: 5.0,
    totalSessions: 180,
    status: 'ACTIVE',
    shiftSchedule: { T2: '08:30 - 17:30', T3: '08:30 - 17:30', T4: '08:30 - 17:30', T5: 'OFF', T6: '08:30 - 17:30', T7: '08:00 - 19:00', CN: '08:00 - 19:00' },
  },
  {
    id: 'emp_nam',
    name: 'Nguyễn Văn Nam',
    phone: '0933 444 555',
    email: 'nam.editor@maisonmipa.vn',
    role: 'EDITOR',
    avatar: '/studio.png',
    skills: ['Lightroom Tone', 'Photoshop Beauty', 'Color Grading'],
    rating: 4.9,
    totalSessions: 310,
    status: 'ACTIVE',
    shiftSchedule: { T2: '08:00 - 17:00', T3: '08:00 - 17:00', T4: '08:00 - 17:00', T5: '08:00 - 17:00', T6: '08:00 - 17:00', T7: 'OFF', CN: 'OFF' },
  },
];

export const INITIAL_CUSTOMERS: CustomerProfile[] = [
  {
    id: 'cust_01',
    userId: 'user_cust_01',
    fullName: 'Nguyễn Minh Anh',
    email: 'minhanh.nguyen@gmail.com',
    phone: '0908 123 456',
    birthday: '1998-09-24',
    instagram: '@minhanh.memories',
    firstVisit: '2026-01-12',
    lastVisit: '2026-08-11',
    totalBookings: 3,
    totalSpent: 6970000,
    notes: 'Khách hàng VIP, thích chụp ánh sáng tự nhiên tone vàng kem ấm.',
  },
  {
    id: 'cust_02',
    userId: 'user_cust_02',
    fullName: 'Trần Bảo Hải',
    email: 'haitran.design@yahoo.com',
    phone: '0918 654 321',
    birthday: '1995-11-15',
    firstVisit: '2026-03-20',
    lastVisit: '2026-08-11',
    totalBookings: 2,
    totalSpent: 4980000,
    notes: 'Thích phong cách tối giản editorial.',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk_001',
    bookingCode: 'MIPA-260811-001',
    customerId: 'cust_01',
    customerName: 'Nguyễn Minh Anh',
    customerPhone: '0908 123 456',
    customerEmail: 'minhanh.nguyen@gmail.com',
    serviceId: 'srv_couple',
    serviceName: 'Couple Photography',
    packageId: 'pkg_signature',
    packageName: 'MIPA SIGNATURE',
    packagePrice: 2490000,
    bookingDate: '2026-08-11',
    startTime: '09:00',
    endTime: '11:00',
    studioId: 'std_room_1',
    studioName: 'Maison Room 01 (Warm French)',
    addons: [INITIAL_ADDONS[4]], // Album 500k
    subtotal: 2990000,
    discount: 0,
    depositAmount: 897000,
    totalAmount: 2990000,
    paymentStatus: 'DEPOSIT_PAID',
    bookingStatus: 'SHOOTING',
    customerNote: 'Kỷ niệm 3 năm yêu nhau, ưu tiên phông rèm lụa vàng kem.',
    occasion: 'Kỷ niệm',
    assignments: [
      { id: 'asg_1', bookingId: 'bk_001', employeeId: 'emp_minh', employeeName: 'Hoàng Minh', assignmentRole: 'PHOTOGRAPHER', startTime: '09:00', endTime: '11:00' },
      { id: 'asg_2', bookingId: 'bk_001', employeeId: 'emp_huong', employeeName: 'Phạm Thanh Hương', assignmentRole: 'MAKEUP', startTime: '08:00', endTime: '09:00' },
    ],
    createdAt: '2026-08-08 14:20',
    updatedAt: '2026-08-11 09:03',
    startTimeActual: '09:05',
  },
  {
    id: 'bk_002',
    bookingCode: 'MIPA-260811-002',
    customerId: 'cust_02',
    customerName: 'Trần Bảo Hải',
    customerPhone: '0918 654 321',
    customerEmail: 'haitran.design@yahoo.com',
    serviceId: 'srv_portrait',
    serviceName: 'Personal Portrait & Concept',
    packageId: 'pkg_basic',
    packageName: 'MIPA BASIC',
    packagePrice: 1290000,
    bookingDate: '2026-08-11',
    startTime: '13:30',
    endTime: '14:30',
    studioId: 'std_room_2',
    studioName: 'Maison Room 02 (Vintage Loft)',
    addons: [INITIAL_ADDONS[0]], // Makeup 400k
    subtotal: 1690000,
    discount: 0,
    depositAmount: 507000,
    totalAmount: 1690000,
    paymentStatus: 'DEPOSIT_PAID',
    bookingStatus: 'CONFIRMED',
    customerNote: 'Chụp ảnh profile doanh nhân tinh tế.',
    occasion: 'Sinh nhật',
    assignments: [
      { id: 'asg_3', bookingId: 'bk_002', employeeId: 'emp_hung', employeeName: 'Trần Hùng', assignmentRole: 'PHOTOGRAPHER', startTime: '13:30', endTime: '14:30' },
    ],
    createdAt: '2026-08-09 10:15',
    updatedAt: '2026-08-09 10:30',
  },
  {
    id: 'bk_003',
    bookingCode: 'MIPA-260810-001',
    customerId: 'cust_01',
    customerName: 'Nguyễn Minh Anh',
    customerPhone: '0908 123 456',
    customerEmail: 'minhanh.nguyen@gmail.com',
    serviceId: 'srv_baby',
    serviceName: 'Baby & Newborn Memories',
    packageId: 'pkg_signature',
    packageName: 'MIPA SIGNATURE',
    packagePrice: 2490000,
    bookingDate: '2026-08-10',
    startTime: '10:00',
    endTime: '12:00',
    studioId: 'std_room_1',
    studioName: 'Maison Room 01 (Warm French)',
    addons: [],
    subtotal: 2490000,
    discount: 249000,
    depositAmount: 747000,
    totalAmount: 2241000,
    paymentStatus: 'FULLY_PAID',
    bookingStatus: 'READY_FOR_REVIEW',
    customerNote: 'Bé tròn 1 tuổi, chuẩn bị bánh kem.',
    assignments: [
      { id: 'asg_4', bookingId: 'bk_003', employeeId: 'emp_hung', employeeName: 'Trần Hùng', assignmentRole: 'PHOTOGRAPHER', startTime: '10:00', endTime: '12:00' },
      { id: 'asg_5', bookingId: 'bk_003', employeeId: 'emp_nam', employeeName: 'Nguyễn Văn Nam', assignmentRole: 'EDITOR', startTime: '13:00', endTime: '17:00' },
    ],
    createdAt: '2026-08-05 16:40',
    updatedAt: '2026-08-10 18:00',
    albumId: 'alb_001',
  },
  {
    id: 'bk_004',
    bookingCode: 'MIPA-260815-001',
    customerId: 'cust_01',
    customerName: 'Nguyễn Minh Anh',
    customerPhone: '0908 123 456',
    customerEmail: 'minhanh.nguyen@gmail.com',
    serviceId: 'srv_wedding',
    serviceName: 'Pre-Wedding & Studio Wedding',
    packageId: 'pkg_premium',
    packageName: 'MIPA PREMIUM LUXURY',
    packagePrice: 3990000,
    bookingDate: '2026-08-15',
    startTime: '14:00',
    endTime: '17:00',
    studioId: 'std_garden',
    studioName: 'Outdoor Maison Garden',
    addons: [INITIAL_ADDONS[0], INITIAL_ADDONS[4]],
    subtotal: 4890000,
    discount: 0,
    depositAmount: 1467000,
    totalAmount: 4890000,
    paymentStatus: 'DEPOSIT_PAID',
    bookingStatus: 'CONFIRMED',
    occasion: 'Cưới',
    assignments: [
      { id: 'asg_6', bookingId: 'bk_004', employeeId: 'emp_minh', employeeName: 'Hoàng Minh', assignmentRole: 'PHOTOGRAPHER', startTime: '14:00', endTime: '17:00' },
      { id: 'asg_7', bookingId: 'bk_004', employeeId: 'emp_huong', employeeName: 'Phạm Thanh Hương', assignmentRole: 'MAKEUP', startTime: '13:00', endTime: '14:00' },
    ],
    createdAt: '2026-08-11 08:30',
    updatedAt: '2026-08-11 08:35',
  },
];

export const INITIAL_ALBUMS: Album[] = [
  {
    id: 'alb_001',
    bookingCode: 'MIPA-260810-001',
    customerName: 'Nguyễn Minh Anh',
    serviceName: 'Baby & Newborn Memories',
    shootDate: '10/08/2026',
    status: 'READY_FOR_REVIEW',
    totalPhotos: 12,
    retouchCount: 3,
    galleryUrl: 'https://maisonmipa.vn/gallery/MIPA-260810-001',
    photos: [
      {
        id: 'p1',
        albumId: 'alb_001',
        url: '/hero.png',
        filename: 'DSC_1021.jpg',
        isFavorite: true,
        retouchRequested: true,
        comment: 'Chỉnh mịn da giúp mẹ & làm da bé hồng tự nhiên nhé',
      },
      {
        id: 'p2',
        albumId: 'alb_001',
        url: '/studio.png',
        filename: 'DSC_1025.jpg',
        isFavorite: true,
        retouchRequested: true,
        comment: 'Tấm này thích nhất ạ!',
      },
      {
        id: 'p3',
        albumId: 'alb_001',
        url: '/hero.png',
        filename: 'DSC_1040.jpg',
        isFavorite: false,
        retouchRequested: true,
        comment: 'Xóa bớt chi tiết nhỏ góc phải',
      },
      {
        id: 'p4',
        albumId: 'alb_001',
        url: '/studio.png',
        filename: 'DSC_1052.jpg',
        isFavorite: true,
        retouchRequested: false,
      },
      {
        id: 'p5',
        albumId: 'alb_001',
        url: '/hero.png',
        filename: 'DSC_1088.jpg',
        isFavorite: false,
        retouchRequested: false,
      },
      {
        id: 'p6',
        albumId: 'alb_001',
        url: '/studio.png',
        filename: 'DSC_1099.jpg',
        isFavorite: true,
        retouchRequested: false,
      },
    ],
  },
];

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 'promo_1',
    code: 'MIPA20',
    discountPercent: 20,
    minOrder: 1500000,
    maxDiscount: 500000,
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    usageCount: 24,
    usageLimit: 100,
    applicableServiceId: 'srv_couple',
    isActive: true,
  },
  {
    id: 'promo_2',
    code: 'SUMMERMEMORY',
    discountPercent: 10,
    minOrder: 1000000,
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    usageCount: 42,
    usageLimit: 200,
    isActive: true,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_1',
    timestamp: '11/08/2026 09:03',
    userId: 'user_manager',
    userName: 'Lê Tấn Phát',
    userRole: 'MANAGER',
    action: 'UPDATE_STATUS',
    details: 'Đã chuyển trạng thái đơn MIPA-260811-001 thành SHOOTING',
    beforeValue: 'CHECKED_IN',
    afterValue: 'SHOOTING',
  },
  {
    id: 'log_2',
    timestamp: '11/08/2026 08:35',
    userId: 'user_cust_01',
    userName: 'Nguyễn Minh Anh',
    userRole: 'CUSTOMER',
    action: 'CREATE_BOOKING',
    details: 'Tạo đơn đặt lịch thành công MIPA-260815-001 (Pre-Wedding)',
    afterValue: 'MIPA-260815-001',
  },
  {
    id: 'log_3',
    timestamp: '10/08/2026 18:00',
    userId: 'user_staff_photographer',
    userName: 'Nguyễn Văn Nam',
    userRole: 'STAFF',
    action: 'UPLOAD_ALBUM',
    details: 'Đã đăng tải 12 ảnh demo cho đơn MIPA-260810-001',
    afterValue: 'READY_FOR_REVIEW',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Booking mới',
    message: 'MIPA-260815-001 vừa hoàn thành chuyển khoản cọc 1.467.000đ',
    timestamp: '08:35',
    read: false,
    type: 'payment',
    targetRole: 'MANAGER',
  },
  {
    id: 'notif_2',
    title: 'Buổi chụp chuẩn bị diễn ra',
    message: 'Lịch chụp Couple 13:30 tại Room 02 với khách Trần Bảo Hải',
    timestamp: '11:00',
    read: false,
    type: 'booking',
    targetRole: 'STAFF',
  },
  {
    id: 'notif_3',
    title: 'Bộ ảnh đã sẵn sàng!',
    message: 'Album ảnh Baby MIPA-260810-001 đã có thể xem & chọn ảnh retouch.',
    timestamp: 'Hôm qua',
    read: true,
    type: 'album',
    targetRole: 'CUSTOMER',
  },
];
